### ISSUE TITLE
just says loading

### ISSUE THREAD

**Issue by GrizzlyKt** [Pandiora/SteamAccountRoboticAssistant#22]
hi i get this error in the extension  Errors
Alarm delay is less than minimum of 1 minutes. In released .crx, alarm "booster-json" will fire in approximately 1 minutes.
Context
_generated_background_page.html
Stack Trace
_generated_background_page.html:0 (anonymous function)
Nothing to see here, move along.
Alarm delay is less than minimum of 1 minutes. In released .crx, alarm "owned-games" will fire in approximately 1 minutes.
Uncaught SyntaxError: Unexpected token u in JSON at position 0

it also just says loading when ive added my details after clicking overview

**Comment by Pandiora** [comment]
Hi @GrizzlyKt ,

did you installed the extension recently? I'm asking because I updated a lot of files today and I'm not sure if I caused new problems to some users who are starting from scratch.

The extension-errors depending the timing errors can be safely ignored. Depending the overview, I'm just asking to ignore it. I'm trying to migrate to a better webinterface (just replace index.html with index2.html on the extension-tab to see what I mean) and it's useless for me to invest my time in things I want to get rid of. Just open another page but not the overview-page and reload the site and the loading-indicator should disappear.

**Comment by Pandiora** [comment]
Alright, quick and dirty fix, since booster-data couldn't be loaded w/o api-key -> replace your functions.js with the one I pushed to this repo now: https://raw.githubusercontent.com/Pandiora/SteamAccountRoboticAssistant/master/js/functions.js
